### ISSUE TITLE
GET params missing

### ISSUE THREAD

**Issue by vimdude** [ewanleith/Wordpress-Server-Configuration-Files#1]
This configuration is missing get parameters.

Line 14 should be changed from:
try_files $uri $uri/ /index.php;

To

try_files $uri $uri/ /index.php?q=$uri&$args;

Else data passed through $_GET will not work.

**Comment by ewanleith** [comment]
You're right of course, thanks. It's not strictly needed for this minimal configuration, but it should be there anyway. I've added it now.
