### ISSUE TITLE
Logs not writing

### ISSUE THREAD

**Issue by corbanb** [ewanleith/Wordpress-Server-Configuration-Files#4]
did you ever have issues with the logs not being written with this setup? since I set this up none of the error logs from php have worked. Any ideas?

**Comment by ewanleith** [comment]
Hmm, good point

In /etc/php5/fpm/php.ini 

look for an "error_log" line, I think it'll be commented out. Add a line

error_log = /var/log/php_errors.log

and save the file, then run

touch /var/log/php_errors_log
chown www-data:www-data /var/log/php_errors.log
service php5-fpm restart

Then it'll log errors! The touch and chown lines might not be necessary but I can't test it right now

Sorry about that.
